### ISSUE TITLE
运行项目

### ISSUE THREAD

**Issue by zl142900** [AspenLuoQiang/ife-css-sprites#1]
你好 ，这个项目怎么运行啊

**Comment by AspenLuoQiang** [comment]
您好，这是一个VUE项目，如果你只是想使用雪碧图功能，可以直接使用[IFE Css Sprites](http://tool.luodao.me/css-sprite)这个在线服务就可以了。如果是想自己搭建一个，那么克隆本项目后，安装依赖后再`yarn run `进行开发或者`yarn run build`进行正式编译即可。

**Comment by zl142900** [comment]
我想自己搭建一个  为什么不是npm run dev啊

**Comment by zl142900** [comment]
以前我没用过  刚才百度了一下。现在我知道了   谢谢
